[theme]
base = "dark"
primaryColor = "#6366F1"
backgroundColor = "#080D17"
secondaryBackgroundColor = "#111827"
textColor = "#E5E7EB"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
address = "0.0.0.0"